### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by lasomethingsomething** [rbarilani/react-simple-inpagenav#1]
This looks like something we can promote to the React Community. WDYT?

**Comment by rbarilani** [comment]
@LappleApple Hi... this component is used to manage the "inpage navigation" in the zalando github io page.  It's my first and only react component ... I did it during my on boarding process to explore React... so it probably contains a lot of mistakes and missing features.

**Comment by lasomethingsomething** [comment]
Ah, I see. Is it dependent on Catwatch, or could it be used out of the box (with some code cleanup)?

**Comment by rbarilani** [comment]
It can be used stand alone. I did a minimal demo site that is linked in the readme: http://zalando.github.io/react-simple-inpagenav/
